name: Send issue to Discord
env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  DISCORD_EMBEDS: '[{"title":"${{EVENT_PAYLOAD.issue.title}}"}]'
on:
  issues:
    types:
      - opened
jobs:
  send_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Actions for Discord
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "New grant application"
            
